model_endpoint: http://localhost:5001/invocations   # model prediction endpoint
data_repo: repo-path    # data repository url
repo_branch: data-branch-name   # the branch name in the data repo where versioned data are kept
current_data_version: v1.0.0    # current data version from the above repo
new_data_version: v1.1.0    # new data version from the above repo
feature_columns: ["mainroad", "guestroom", "basement", "hotwaterheating",
                       "airconditioning", "prefarea", "furnishingstatus",
                       "area", "bedrooms", "bathrooms", "stories", "parking"]   # feature columns to be used form the data
label_column: "price"   # label column name
report_location: "s3"   # where to save the evidently report
report_name: evidently_report.html    # evidently report file name
current_data_local_path: ../artefacts/HousingData.csv   # local path where the pulled current data is kept
new_data_local_path: ../artefacts/HousingData-new.csv   # local path where the pulled new data is kept
